version: "3"

services:
  zookeeper:
    image: "bitnami/zookeeper:3.7.0"
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file: .env
    networks:
      - product_alert_system_default

  kafka:
    image: "bitnami/kafka:2.8.0"
    container_name: kafka
    ports:
      - "9093:9093"
    expose:
      - "9093"
    env_file:
      - .env
    depends_on:
      - zookeeper
    networks:
      - product_alert_system_default
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - kafka
    networks:
      - product_alert_system_default
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db

    env_file: .env
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - product_alert_system_default
    ports:
      - "3306:3306"
  cache:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - product_alert_system_default
  ss:
    build:
      context: ./ss
      dockerfile: Dockerfile.dev
    container_name: ss
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./ss/src:/app/src
    networks:
      - product_alert_system_default

  as:
    build:
      context: ./as
      dockerfile: Dockerfile.dev
    container_name: as
    ports:
      - "4444:4444"
    env_file:
      - .env
    volumes:
      - ./as/src:/app/src
    networks:
      - product_alert_system_default
  ds:
    build:
      context: ./ds
      dockerfile: Dockerfile
    container_name: ds
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - "./ds/:/app/"
    networks:
      - product_alert_system_default
    depends_on:
      - kafka
      - ss

  cs:
    build:
      context: ./cs
      dockerfile: Dockerfile
    container_name: cs
    ports:
      - "7777:7777"
    env_file:
      - .env
    volumes:
      - "./cs/:/app/"
    networks:
      - product_alert_system_default
    depends_on:
      - kafka
      - ds
      - cache

networks:
  product_alert_system_default:
    driver: bridge
