version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    env_file:
      .env
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - product_alert_system_default

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    
    env_file:
      .env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - product_alert_system_default
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    
    env_file:
      .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pas
      MYSQL_USER: pas
      MYSQL_PASSWORD: pas
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - product_alert_system_default
    ports:
      - "3306:3306"
  cache:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    networks:
      - product_alert_system_default
  ss:
    build:
      context: ./ss
      dockerfile: Dockerfile.dev
    container_name: ss
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./ss/src:/app/src
    networks:
      - product_alert_system_default
  
  as:
    build:
      context: ./as
      dockerfile: Dockerfile.dev
    container_name: as
    ports:
      - "4444:4444"
    env_file:
      - .env
    volumes:
      - ./as/src:/app/src
    networks:
      - product_alert_system_default

networks:
  product_alert_system_default:
    driver: bridge
